# Generated by Django 2.0 on 2017-12-09 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Data')),
                ('hora_inicio', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Inicio')),
                ('hora_final', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fim')),
                ('nome_paciente', models.CharField(max_length=150, verbose_name='Paciente')),
                ('procedimento', models.CharField(max_length=250, verbose_name='Procedimento')),
            ],
        ),
    ]
