# Generated by Django 2.0 on 2017-12-09 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
