# Generated by Django 2.0 on 2017-12-11 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_final',
            field=models.TimeField(default=10, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(default=10, verbose_name='Inicio'),
        ),
    ]
