# Generated by Django 2.0 on 2017-12-09 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_auto_20171209_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora_final',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Inicio'),
        ),
    ]
