# Generated by Django 2.0 on 2017-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_auto_20171211_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='nome_paciente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='procedimento',
            field=models.CharField(blank=True, max_length=250, verbose_name='Procedimento'),
        ),
    ]
