# Generated by Django 2.0 on 2017-12-09 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_auto_20171209_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora_final',
            field=models.TextField(blank=True, default=datetime.datetime.now, verbose_name='Fim'),
        ),
    ]
