# Generated by Django 2.0 on 2017-12-09 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_auto_20171209_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 9, 20, 25, 5, 232607), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 12, 9, 20, 25, 5, 232689), verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 12, 9, 20, 25, 5, 232657), verbose_name='Inicio'),
        ),
    ]
