# Generated by Django 2.0 on 2017-12-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_auto_20171209_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora_final',
            field=models.TimeField(blank=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(blank=True, verbose_name='Inicio'),
        ),
    ]
