# Generated by Django 2.0 on 2017-12-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_auto_20171209_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(auto_now_add=True, verbose_name='Inicio'),
        ),
    ]
