# Generated by Django 2.0 on 2017-12-09 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_auto_20171209_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.datetime.now, verbose_name='Inicio'),
        ),
    ]
