# Generated by Django 2.0 on 2017-12-09 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_auto_20171209_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.datetime.utcnow, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.datetime.utcnow, verbose_name='Inicio'),
        ),
    ]
