# Generated by Django 2.0 on 2017-12-09 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0014_auto_20171209_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_final',
            field=models.TimeField(auto_now_add=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(auto_now_add=True, verbose_name='Inicio'),
        ),
    ]
