# Generated by Django 2.0 on 2017-12-09 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0015_auto_20171209_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(blank=True, default=datetime.time(21, 28, 40, 224286), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(default=21, verbose_name='Inicio'),
        ),
    ]
