# Generated by Django 2.0 on 2017-12-09 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0017_auto_20171209_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data'),
        ),
    ]
